language: java
install: mvn clean install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
jdk:
  - openjdk8
branch:
  - master
deploy:
  provider: script
  script: "cp .maven.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
